# Generated by Django 3.2.4 on 2021-08-14 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('subid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(default='', upload_to='course/images')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('quesid', models.AutoField(primary_key=True, serialize=False)),
                ('questext', models.TextField(max_length=5000)),
                ('points', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('opid', models.AutoField(primary_key=True, serialize=False)),
                ('opttext', models.TextField(default='', max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
    ]
